name: givt_app_kids_game
description: Givt4Kids Game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^3.0.1
  equatable: ^2.0.5
  flame: ^1.6.0
  flame_audio: ^1.4.0
  flame_behaviors: ^0.2.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  intl: ^0.17.0
  mockingjay: ^0.3.0
  provider: ^6.0.5
  flutter_fortune_wheel: ^1.2.0
  flutter_svg: ^1.1.6
  loading_indicator: ^3.1.0
  lottie: ^2.2.0

dev_dependencies:
  flame_test: ^1.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/lotties/
